#!/bin/bash
echo "🧬 [NANOTEC] Starter 12-timers selvutviklingssløyfe..."
START=$(date +%s)
STOP_AFTER=$((12 * 60 * 60))

VAULT=~/GinieSystem/Vault
SCRIPTS=~/GinieSystem/Scripts
LOG=$VAULT/nanotec_loop_$(date +%Y%m%d_%H%M).log
MEM=$VAULT/nanotec.memory
IMPROVE_DIR=~/GinieSystem/NanoTech/Autogenerated

touch "$MEM"
echo "🧠 Init: $(date)" >> "$MEM"

while true; do
  NOW=$(date +%s)
  RUNTIME=$((NOW - START))
  if [ $RUNTIME -gt $STOP_AFTER ]; then
    echo "✅ [NANOTEC] Fullført 12t utviklingsloop." | tee -a "$LOG"
    break
  fi

  echo "🔁 [$(date +%H:%M:%S)] Loop..." | tee -a "$LOG"

  # Oppdag nye eller endrede filer
  CHANGES=$(find "$SCRIPTS" -type f -mmin -10)
  echo "[ENDRINGER]: $CHANGES" >> "$LOG"

  # Lagrer refleksjon
  echo "[REFLEKSJON $(date)] Selvutvikling i gang." >> "$MEM"

  # Forbedre ett tilfeldig skript
  for file in $(find "$SCRIPTS" -type f -name "*.sh" | shuf | head -n 1); do
    base=$(basename "$file")
    out="$IMPROVE_DIR/${base%.sh}_$(date +%H%M%S).sh"
    echo "# Improved: $base $(date)" > "$out"
    sed 's/#/##/g' "$file" >> "$out"
    chmod +x "$out"
    echo "✏️ Mutasjon: $out" >> "$LOG"
    break
  done

  # Snapshot av spesifikasjon
  if [ -f "$VAULT/giniesystem.spec" ]; then
    cp "$VAULT/giniesystem.spec" "$VAULT/spec_snapshot_$(date +%H%M%S).spec"
  fi

  sleep 300
done
